/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cs2212.gis_project;

import java.awt.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 * This class has functions critical to the application and handles all GUI
 * operations.
 *
 * @author nlobo9
 */
public class Application extends javax.swing.JFrame {

    private String activeMap;
    private User activeUser;    
    private boolean unsavedChanges = false;
//    private String[] mapFiles = { "maps/mc0.png", "maps/mc1.png", "maps/mc2.png", "maps/mc3.png", "maps/mc4.png"};
    //private Map activeMapObj;
    //private Map map = new Map("MIDDLESEX");
    private POI[] poiList;
    private int[] favouriteIDs;
    private POI[] userCustomPOIList;
    
    private HashMap<Category, Boolean> activeLayers = new HashMap<>();
    private GIS_System gis_system = GIS_System.getInstance();

    /**
     * Creates new form GUI
     */
    public Application() {
        initComponents();
        buildingSelectPanel.setVisible(false);
        buildingPanel.setVisible(false);
        layerPanel.setVisible(false);
        customPanel.setVisible(false);
        mapImageScrollPane.setVisible(false);
        //activeMap = new Map();
        loginFailLabel.setVisible(false);
        blackMenuPanel.setVisible(false);
        //set all layer types to active
        this.activeLayers.put(Category.CLASSROOM, true);
        this.activeLayers.put(Category.RESTAURANT, true);
        this.activeLayers.put(Category.LAB, true);
        this.activeLayers.put(Category.WASHROOM, true);
        this.activeLayers.put(Category.ELEVATOR, true);
    }

    /**
     * Start the application (after login).
     */
    public void start(String chosenBuilding) {
        System.out.println(chosenBuilding + " chosen...");
        buildingSelectPanel.setVisible(false);
        mapPanel.setVisible(true);
        mapImageScrollPane.setVisible(true);
        blackMenuPanel.setVisible(true);
        
        //set map image for chosen building. Default to ground floor for each
        
        //read poi's into arrays
        
        
        //display the appropriate pois... all layers selected by default
        classroomCheckbox.setSelected(true);
        washroomCheckbox.setSelected(true);
        labCheckbox.setSelected(true);
        restaurantCheckbox.setSelected(true);
        elevatorCheckbox.setSelected(true);
        
//        for (POI p : POI[] poiList) {
//            //get p's (x,y)
//            //create a jlabel at that area with no text and the icon for p's layer type.
//        }
        
        
    }

    /**
     * Exit the application.
     */
    public void exit() {
        //TODO: need to somehow override the windowlister for this jframe. Cant right now beause netbeans doesnt allow me to edit the frame on exit action.
        //look into this...
        //check for unsaved changes
        
        if (unsavedChanges) {
            JOptionPane.showMessageDialog(this, "You have unsaved changes.", "Unsaved Changes", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * Finds the desired POI object from the current map.
     *
     * @param search name of the POI eg. "MC 105"
     * @return reference to desired POI object
     */
    public POI findPOI(String search) {
        return null;
    }
    /**
     * Changes the map that is being displayed.
     *
     * @param name
     */
    public void changeMap(String buildingName, String floorLevel) {
        //change the image icon for the JLabel representing the map image. 
        String filepath = "/maps/" + buildingName.toUpperCase() + "_" + floorLevel.toUpperCase();
        filepath = filepath.replaceAll(" ", "_") + ".png";
        System.out.println(filepath);
        mapImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(filepath)));
        
    }

    /**
     * Returns the currently displayed map name
     *
     * @return name of active map
     */
    public String getActiveMap() {
        return this.activeMap;
    }

    /**
     * Alters the visibility of a POI layer
     *
     * @param type the group of layers to alter (Classroom, Lab, etc.)
     * @param active true to make visible, false to make invisible
     */
    public void toggleLayer(Category type, boolean active) {
        //update the activeLayers hashmap 
        this.activeLayers.put(type, active);
        System.out.println(type + " layer set to " + Boolean.toString(active));
        
        //repaint the map to only include active layers
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        usernameTextField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        loginPageLabel = new javax.swing.JLabel();
        loginFailLabel = new javax.swing.JLabel();
        westernLogoLabel = new javax.swing.JLabel();
        group42Label = new javax.swing.JLabel();
        buildingSelectPanel = new javax.swing.JPanel();
        selectBuildingLabel = new javax.swing.JLabel();
        mcButton = new javax.swing.JButton();
        mcLabel = new javax.swing.JLabel();
        ahButton = new javax.swing.JButton();
        ahLabel = new javax.swing.JLabel();
        ncbLabel = new javax.swing.JLabel();
        ncbButton = new javax.swing.JButton();
        westernLogo2 = new javax.swing.JLabel();
        mapPanel = new javax.swing.JPanel();
        mapImageScrollPane = new javax.swing.JScrollPane();
        mapImageLabel = new javax.swing.JLabel();
        blackMenuPanel = new javax.swing.JPanel();
        helpButton = new javax.swing.JButton();
        buildingMenuButton = new javax.swing.JButton();
        layersMenuButton = new javax.swing.JButton();
        customMenuButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        buildingPanel = new javax.swing.JPanel();
        buildingChangeLabel = new javax.swing.JLabel();
        closeBuilding = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        buildingTree = new javax.swing.JTree();
        layerPanel = new javax.swing.JPanel();
        layerSelectLabel = new javax.swing.JLabel();
        closeLayer = new javax.swing.JLabel();
        classroomCheckbox = new javax.swing.JCheckBox();
        restaurantCheckbox = new javax.swing.JCheckBox();
        labCheckbox = new javax.swing.JCheckBox();
        washroomCheckbox = new javax.swing.JCheckBox();
        elevatorCheckbox = new javax.swing.JCheckBox();
        customPanel = new javax.swing.JPanel();
        customSelectLabel = new javax.swing.JLabel();
        closeCustom = new javax.swing.JLabel();
        createPOIButton = new javax.swing.JButton();
        editPOIButton = new javax.swing.JButton();
        deletePOIButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });

        usernameLabel.setText("Username");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        passwordLabel.setText("Password");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        loginPageLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        loginPageLabel.setText("Login Page");

        loginFailLabel.setForeground(new java.awt.Color(255, 0, 0));
        loginFailLabel.setText("Username and/or password is incorrect. Try again.");

        westernLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/westernLogo.png"))); // NOI18N

        group42Label.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        group42Label.setText("Group 42 - CS2212 GIS Project");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginPageLabel)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginFailLabel)
                            .addComponent(loginButton)
                            .addComponent(passwordLabel)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernameLabel)
                                .addComponent(usernameTextField)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(116, 116, 116)
                        .addComponent(westernLogoLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(group42Label)
                .addGap(204, 204, 204))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(loginPageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(group42Label)
                .addGap(99, 99, 99)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passwordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginButton)
                        .addGap(24, 24, 24)
                        .addComponent(loginFailLabel))
                    .addComponent(westernLogoLabel))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        selectBuildingLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        selectBuildingLabel.setText("Select a Building");

        mcButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mcButton.setText("Middlesex College");
        mcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcButtonActionPerformed(evt);
            }
        });

        mcLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        mcLabel.setText("MC");

        ahButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ahButton.setText("Alumni Hall");
        ahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ahButtonActionPerformed(evt);
            }
        });

        ahLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ahLabel.setText("AH");

        ncbLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ncbLabel.setText("NCB");

        ncbButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ncbButton.setText("North Campus Building");
        ncbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ncbButtonActionPerformed(evt);
            }
        });

        westernLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/westernLogo.png"))); // NOI18N

        javax.swing.GroupLayout buildingSelectPanelLayout = new javax.swing.GroupLayout(buildingSelectPanel);
        buildingSelectPanel.setLayout(buildingSelectPanelLayout);
        buildingSelectPanelLayout.setHorizontalGroup(
            buildingSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildingSelectPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(buildingSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectBuildingLabel)
                    .addComponent(mcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(buildingSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buildingSelectPanelLayout.createSequentialGroup()
                        .addComponent(ahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(ncbButton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(westernLogo2))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(buildingSelectPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(mcLabel)
                .addGap(295, 295, 295)
                .addComponent(ahLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ncbLabel)
                .addGap(204, 204, 204))
        );
        buildingSelectPanelLayout.setVerticalGroup(
            buildingSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildingSelectPanelLayout.createSequentialGroup()
                .addGroup(buildingSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buildingSelectPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(selectBuildingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buildingSelectPanelLayout.createSequentialGroup()
                        .addContainerGap(186, Short.MAX_VALUE)
                        .addComponent(westernLogo2)
                        .addGap(58, 58, 58)))
                .addGroup(buildingSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncbButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(buildingSelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncbLabel)
                    .addComponent(ahLabel)
                    .addComponent(mcLabel))
                .addGap(259, 259, 259))
        );

        mapImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maps/MIDDLESEX_COLLEGE_LEVEL_2.png"))); // NOI18N
        mapImageScrollPane.setViewportView(mapImageLabel);

        blackMenuPanel.setBackground(new java.awt.Color(0, 0, 0));

        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/help.png"))); // NOI18N
        helpButton.setBorderPainted(false);
        helpButton.setContentAreaFilled(false);
        helpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpButtonMouseClicked(evt);
            }
        });
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        buildingMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/building.png"))); // NOI18N
        buildingMenuButton.setBorderPainted(false);
        buildingMenuButton.setContentAreaFilled(false);
        buildingMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingMenuButtonActionPerformed(evt);
            }
        });

        layersMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/layers.png"))); // NOI18N
        layersMenuButton.setBorderPainted(false);
        layersMenuButton.setContentAreaFilled(false);
        layersMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layersMenuButtonActionPerformed(evt);
            }
        });

        customMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/create.png"))); // NOI18N
        customMenuButton.setBorderPainted(false);
        customMenuButton.setContentAreaFilled(false);
        customMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customMenuButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("4 °C ");

        javax.swing.GroupLayout blackMenuPanelLayout = new javax.swing.GroupLayout(blackMenuPanel);
        blackMenuPanel.setLayout(blackMenuPanelLayout);
        blackMenuPanelLayout.setHorizontalGroup(
            blackMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blackMenuPanelLayout.createSequentialGroup()
                .addGroup(blackMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(blackMenuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(blackMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(helpButton)
                            .addComponent(buildingMenuButton)
                            .addComponent(layersMenuButton)
                            .addComponent(customMenuButton)))
                    .addGroup(blackMenuPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        blackMenuPanelLayout.setVerticalGroup(
            blackMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blackMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buildingMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layersMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(helpButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(35, 35, 35))
        );

        buildingPanel.setBackground(new java.awt.Color(255, 153, 153));

        buildingChangeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buildingChangeLabel.setText("Buildings");

        closeBuilding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-close-window-16.png"))); // NOI18N
        closeBuilding.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBuildingMouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Middlesex College");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 4");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 5");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 6");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Alumni Hall");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 4");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("North Campus Building");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 4");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Level 5");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        buildingTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        buildingTree.setRootVisible(false);
        buildingTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buildingTreeMouseClicked(evt);
            }
        });
        buildingTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                buildingTreeValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(buildingTree);

        javax.swing.GroupLayout buildingPanelLayout = new javax.swing.GroupLayout(buildingPanel);
        buildingPanel.setLayout(buildingPanelLayout);
        buildingPanelLayout.setHorizontalGroup(
            buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buildingPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(buildingPanelLayout.createSequentialGroup()
                        .addComponent(buildingChangeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeBuilding))))
        );
        buildingPanelLayout.setVerticalGroup(
            buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildingPanelLayout.createSequentialGroup()
                .addGroup(buildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buildingPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buildingChangeLabel))
                    .addComponent(closeBuilding))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layerPanel.setBackground(new java.awt.Color(255, 153, 153));

        layerSelectLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        layerSelectLabel.setText("Layers");

        closeLayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-close-window-16.png"))); // NOI18N
        closeLayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLayerMouseClicked(evt);
            }
        });

        classroomCheckbox.setText("Classroom");
        classroomCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classroomCheckboxActionPerformed(evt);
            }
        });

        restaurantCheckbox.setText("Restaurant");
        restaurantCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurantCheckboxActionPerformed(evt);
            }
        });

        labCheckbox.setText("Lab");
        labCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labCheckboxActionPerformed(evt);
            }
        });

        washroomCheckbox.setText("Washroom");
        washroomCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                washroomCheckboxActionPerformed(evt);
            }
        });

        elevatorCheckbox.setText("Elevator");
        elevatorCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevatorCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layerPanelLayout = new javax.swing.GroupLayout(layerPanel);
        layerPanel.setLayout(layerPanelLayout);
        layerPanelLayout.setHorizontalGroup(
            layerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layerPanelLayout.createSequentialGroup()
                        .addComponent(layerSelectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeLayer))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layerPanelLayout.createSequentialGroup()
                        .addGroup(layerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(elevatorCheckbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(washroomCheckbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labCheckbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(restaurantCheckbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(classroomCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layerPanelLayout.setVerticalGroup(
            layerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerPanelLayout.createSequentialGroup()
                .addGroup(layerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(layerSelectLabel))
                    .addComponent(closeLayer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classroomCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(restaurantCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(washroomCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(elevatorCheckbox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customPanel.setBackground(new java.awt.Color(255, 153, 153));

        customSelectLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customSelectLabel.setText("Custom");

        closeCustom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-close-window-16.png"))); // NOI18N
        closeCustom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeCustomMouseClicked(evt);
            }
        });

        createPOIButton.setText("Create POI");
        createPOIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPOIButtonActionPerformed(evt);
            }
        });

        editPOIButton.setText("Edit POI");
        editPOIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPOIButtonActionPerformed(evt);
            }
        });

        deletePOIButton.setText("Delete POI");
        deletePOIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePOIButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customPanelLayout = new javax.swing.GroupLayout(customPanel);
        customPanel.setLayout(customPanelLayout);
        customPanelLayout.setHorizontalGroup(
            customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customSelectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeCustom))
            .addComponent(createPOIButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(editPOIButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deletePOIButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        customPanelLayout.setVerticalGroup(
            customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanelLayout.createSequentialGroup()
                .addGroup(customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customSelectLabel))
                    .addComponent(closeCustom))
                .addGap(18, 18, 18)
                .addComponent(createPOIButton)
                .addGap(18, 18, 18)
                .addComponent(editPOIButton)
                .addGap(18, 18, 18)
                .addComponent(deletePOIButton)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapPanelLayout.createSequentialGroup()
                .addComponent(blackMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buildingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(layerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapImageScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE))
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(blackMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapPanelLayout.createSequentialGroup()
                .addComponent(buildingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 131, Short.MAX_VALUE))
            .addComponent(mapImageScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(buildingSelectPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mapPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buildingSelectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        loginFailLabel.setVisible(false);
        System.out.println("Attempting to login...");
        System.out.println(usernameTextField.getText());
        System.out.println(String.valueOf(passwordField.getPassword()));

        // login with user's credentials, else handle login failure
//        if (gis_system.login(usernameTextField.getText(), String.valueOf(passwordField.getPassword()))) {
          if (true) {
            System.out.println("Login successful.");
            //login success. Remove login page components and move to application UI
            for (Component c : loginPanel.getComponents()) {
                loginPanel.remove(c);
            }
            loginPanel.repaint();
            loginPanel.setVisible(false);
            buildingSelectPanel.setVisible(true);
            
        } else {
            System.out.println("Login Failed.");
            loginFailLabel.setVisible(true);
        }

    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void mcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcButtonActionPerformed
        // TODO add your handling code here:
        start("MIDDLESEX COLLEGE");
    }//GEN-LAST:event_mcButtonActionPerformed

    private void ahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ahButtonActionPerformed
        // TODO add your handling code here:
        start("ALUMNI HALL");
    }//GEN-LAST:event_ahButtonActionPerformed

    private void ncbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ncbButtonActionPerformed
        // TODO add your handling code here:
        start("NORTH CAMPUS BUILDING");
    }//GEN-LAST:event_ncbButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Help Screen");
    }//GEN-LAST:event_helpButtonActionPerformed

    private void buildingMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingMenuButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Building");
        buildingPanel.setVisible(true);
        layerPanel.setVisible(false);
        customPanel.setVisible(false);
    }//GEN-LAST:event_buildingMenuButtonActionPerformed

    private void layersMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layersMenuButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Layer");        
        buildingPanel.setVisible(false);
        layerPanel.setVisible(true);
        customPanel.setVisible(false);

    }//GEN-LAST:event_layersMenuButtonActionPerformed

    private void customMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customMenuButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Create");
        buildingPanel.setVisible(false);
        layerPanel.setVisible(false);
        customPanel.setVisible(true);

    }//GEN-LAST:event_customMenuButtonActionPerformed

    private void closeBuildingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBuildingMouseClicked
        // TODO add your handling code here:
        buildingPanel.setVisible(false);
        layerPanel.setVisible(false);
        customPanel.setVisible(false);
    }//GEN-LAST:event_closeBuildingMouseClicked

    private void closeLayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLayerMouseClicked
        // TODO add your handling code here:
        buildingPanel.setVisible(false);
        layerPanel.setVisible(false);
        customPanel.setVisible(false);
    }//GEN-LAST:event_closeLayerMouseClicked

    private void closeCustomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeCustomMouseClicked
        // TODO add your handling code here:        
        buildingPanel.setVisible(false);
        layerPanel.setVisible(false);
        customPanel.setVisible(false);
    }//GEN-LAST:event_closeCustomMouseClicked

    private void buildingTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingTreeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buildingTreeMouseClicked

    private void buildingTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_buildingTreeValueChanged
        // TODO add your handling code here:
        //get selected node from Building JTree
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) buildingTree.getLastSelectedPathComponent();
        
        //change map to desired building and floor
        String buildingName = node.getParent().toString();
        String floorLevel = node.toString();
        //only change map if a floor was selected as well
        if (!buildingName.equalsIgnoreCase("root")) {
            changeMap(buildingName, floorLevel);
            System.out.println("Changed map to " + buildingName + " " + floorLevel);
        }
        
    }//GEN-LAST:event_buildingTreeValueChanged

    private void helpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseClicked
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, "Current User: user.getName(). more info...", "Help", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_helpButtonMouseClicked

    private void classroomCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classroomCheckboxActionPerformed
        // TODO add your handling code here:
        toggleLayer(Category.CLASSROOM, classroomCheckbox.isSelected());
    }//GEN-LAST:event_classroomCheckboxActionPerformed

    private void restaurantCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurantCheckboxActionPerformed
        // TODO add your handling code here:
        toggleLayer(Category.RESTAURANT, restaurantCheckbox.isSelected());
    }//GEN-LAST:event_restaurantCheckboxActionPerformed

    private void labCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labCheckboxActionPerformed
        // TODO add your handling code here:
        toggleLayer(Category.LAB, labCheckbox.isSelected());
    }//GEN-LAST:event_labCheckboxActionPerformed

    private void washroomCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_washroomCheckboxActionPerformed
        // TODO add your handling code here:
        toggleLayer(Category.WASHROOM, washroomCheckbox.isSelected());
    }//GEN-LAST:event_washroomCheckboxActionPerformed

    private void elevatorCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevatorCheckboxActionPerformed
        // TODO add your handling code here:
        toggleLayer(Category.ELEVATOR, elevatorCheckbox.isSelected());
    }//GEN-LAST:event_elevatorCheckboxActionPerformed

    private void createPOIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPOIButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPOIButtonActionPerformed

    private void editPOIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPOIButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPOIButtonActionPerformed

    private void deletePOIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePOIButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletePOIButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ahButton;
    private javax.swing.JLabel ahLabel;
    private javax.swing.JPanel blackMenuPanel;
    private javax.swing.JLabel buildingChangeLabel;
    private javax.swing.JButton buildingMenuButton;
    private javax.swing.JPanel buildingPanel;
    private javax.swing.JPanel buildingSelectPanel;
    private javax.swing.JTree buildingTree;
    private javax.swing.JCheckBox classroomCheckbox;
    private javax.swing.JLabel closeBuilding;
    private javax.swing.JLabel closeCustom;
    private javax.swing.JLabel closeLayer;
    private javax.swing.JButton createPOIButton;
    private javax.swing.JButton customMenuButton;
    private javax.swing.JPanel customPanel;
    private javax.swing.JLabel customSelectLabel;
    private javax.swing.JButton deletePOIButton;
    private javax.swing.JButton editPOIButton;
    private javax.swing.JCheckBox elevatorCheckbox;
    private javax.swing.JLabel group42Label;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox labCheckbox;
    private javax.swing.JPanel layerPanel;
    private javax.swing.JLabel layerSelectLabel;
    private javax.swing.JButton layersMenuButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginFailLabel;
    private javax.swing.JLabel loginPageLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel mapImageLabel;
    private javax.swing.JScrollPane mapImageScrollPane;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JButton mcButton;
    private javax.swing.JLabel mcLabel;
    private javax.swing.JButton ncbButton;
    private javax.swing.JLabel ncbLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JCheckBox restaurantCheckbox;
    private javax.swing.JLabel selectBuildingLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JCheckBox washroomCheckbox;
    private javax.swing.JLabel westernLogo2;
    private javax.swing.JLabel westernLogoLabel;
    // End of variables declaration//GEN-END:variables
}
